import { test as base, _electron, type ElectronApplication } from '@playwright/test'
import { join } from 'node:path'
import { mkdtempSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { startCanary, type Canary } from './canary.js'

// Mirror of the main-process CageEvent union (see src/main/events.ts). Redefined
// locally so the test bundle never imports main/electron code.
export type CageEvent =
  | { type: 'blocked-request'; url: string; resourceType?: string }
  | { type: 'navigation-blocked'; url: string; kind: 'navigate' | 'redirect' }
  | { type: 'window-open-denied'; url: string }
  | { type: 'permission-denied'; permission: string; via: 'request' | 'check' }
  | { type: 'emit'; channel: string; bytes: number; hash: string }
  | { type: 'emit-rejected'; reason: string }
  | { type: 'att-request'; name: string; status: number; range: string | null }
  | {
      type: 'draft-recorded'
      draftType: string
      att: Record<string, { h: string; m: string; n: number }>
      argsBytes: number
      blobBytes: number
    }
  | { type: 'sandbox-state'; envDisabled: boolean; argvNoSandbox: boolean }

/** Main-process log stats — lets a flood test assert the log stayed bounded. */
export interface CageStats {
  eventsLength: number
  dropped: number
  testEmitsLength: number
  /** Total serialized size of the event log, in bytes. Proves emit payloads
   *  are not retained: bytes-sent can dwarf this while it stays small. */
  eventsBytes: number
}

export interface Bounds {
  chrome: { x: number; y: number; width: number; height: number } | null
  cage: { x: number; y: number; width: number; height: number } | null
  window: { x: number; y: number; width: number; height: number } | null
}

const THINGS_DIR = join(__dirname, 'things')
const FIXTURES_DIR = join(__dirname, 'fixtures')
const MAIN = join(__dirname, '..', 'out', 'main', 'index.js')

export function thingPath(name: string): string {
  return join(THINGS_DIR, name)
}

/** An attachment fed through the harness's admission-lite: `file` is a name
 *  under test/fixtures (generated by global-setup). */
export interface AttachmentSpec {
  name: string
  file: string
  mime: string
}

export interface CageHandle {
  app: ElectronApplication
  /** The per-launch CAS directory — what the persistent store writes into. */
  casDir: string
  /** Hex hashes present in the persistent CAS (empty => nothing hit disk). */
  casBlobs(): string[]
  /** Snapshot of the main-process event log, read from OUTSIDE the renderer. */
  events(): Promise<CageEvent[]>
  /** Bounded-log stats (length, dropped count, serialized size). */
  stats(): Promise<CageStats>
  /** Ground-truth OS-sandbox state recorded by the app at startup. */
  sandboxState(): Promise<{ envDisabled: boolean; argvNoSandbox: boolean } | null>
  /** Resolve with the data of the first emit seen on `channel`. */
  waitForEmit(channel: string, timeoutMs?: number): Promise<unknown>
  /** All emit payloads seen on `channel` so far. */
  emitsOn(channel: string): Promise<unknown[]>
  bounds(): Promise<Bounds>
  close(): Promise<void>
}

export interface LaunchOptions {
  /** Filename under test/things (becomes the primary cage's content). */
  thing: string
  /** manifest.args for the primary thing: getArgs().args. Canary is merged in. */
  args?: Record<string, unknown>
  /** manifest.type (display hint); defaults to 'test' in the harness. */
  type?: string
  /** Attachments admitted for the primary thing. */
  attachments?: AttachmentSpec[]
  /** Sealed thing: attachments serve from memory, NEVER the persistent CAS. */
  sealed?: boolean
  /** Optional second cage in the same run (fresh partition) — storage tests. */
  thing2?: string
  args2?: Record<string, unknown>
  /** Provide a canary so the thing can try (and fail) to beacon to it. */
  canary?: Canary
  /** Extra env for the app (e.g. draft-cap overrides for abuse tests). */
  extraEnv?: Record<string, string>
}

async function readEvents(app: ElectronApplication): Promise<CageEvent[]> {
  return app.evaluate(async (electron) => {
    const cage = (electron.app as unknown as { __cage?: { events: unknown[] } }).__cage
    return (cage ? cage.events : []) as never
  })
}

async function readTestEmits(app: ElectronApplication): Promise<{ channel: string; data: unknown }[]> {
  return app.evaluate(async (electron) => {
    const cage = (electron.app as unknown as { __cage?: { testEmits: unknown[] } }).__cage
    return (cage ? cage.testEmits : []) as never
  })
}

export async function launch(opts: LaunchOptions): Promise<CageHandle> {
  const env: Record<string, string> = { ...process.env } as Record<string, string>
  // P0-1: never inherit the sandbox-disable escape hatch from the developer's
  // shell or CI. If it were set, the whole suite would run with Layer 1 off and
  // still report green. The app records ground truth (sandbox-state) and the
  // suite asserts on it; scrubbing here keeps that assertion honest.
  delete env.ELECTRON_DISABLE_SANDBOX
  // Retain emit payloads for assertions (test-only capture, bounded) and keep
  // the stderr mirror quiet so a flood test does not spew thousands of writes.
  env.CAGE_TEST_CAPTURE = '1'
  env.CAGE_QUIET = '1'
  env.CAGE_THING = thingPath(opts.thing)
  env.CAGE_ARGS = JSON.stringify({ ...(opts.args ?? {}), canary: canaryArg(opts.canary) })
  if (opts.type) env.CAGE_TYPE = opts.type
  if (opts.attachments) {
    env.CAGE_ATTACHMENTS = JSON.stringify(
      opts.attachments.map((a) => ({ name: a.name, path: join(FIXTURES_DIR, a.file), mime: a.mime }))
    )
  }
  if (opts.sealed) env.CAGE_SEALED = '1'
  if (opts.thing2) {
    env.CAGE_THING2 = thingPath(opts.thing2)
    env.CAGE_ARGS2 = JSON.stringify({ ...(opts.args2 ?? {}), canary: canaryArg(opts.canary) })
  }
  // Every launch gets its own CAS dir so tests can assert exactly what was
  // (or was not) persisted to disk by this run.
  const casDir = mkdtempSync(join(tmpdir(), 'cage-cas-'))
  env.CAGE_CAS_DIR = casDir
  Object.assign(env, opts.extraEnv ?? {})

  // NOTE (P0-1): Playwright's `_electron.launch` injects `--no-sandbox` by
  // default, so the OS sandbox (Layer 1) is OFF for the suite. The behavioral
  // guarantees do not depend on it; the app records this and the harness-
  // integrity test + reporter surface it, so the wall never overstates what was
  // proven. To run WITH the OS sandbox, pass `chromiumSandbox: true` here on a
  // host that can initialize it.
  const app = await _electron.launch({ args: [MAIN], env })

  const handle: CageHandle = {
    app,
    casDir,
    casBlobs() {
      try {
        return readdirSync(join(casDir, 'blobs'))
      } catch {
        return []
      }
    },
    events: () => readEvents(app),
    stats: () =>
      app.evaluate(async (electron) => {
        const cage = (
          electron.app as unknown as {
            __cage?: { events: unknown[]; dropped: number; testEmits: unknown[] }
          }
        ).__cage
        if (!cage) return { eventsLength: 0, dropped: 0, testEmitsLength: 0, eventsBytes: 0 } as never
        return {
          eventsLength: cage.events.length,
          dropped: cage.dropped,
          testEmitsLength: cage.testEmits.length,
          eventsBytes: JSON.stringify(cage.events).length
        } as never
      }),
    async sandboxState() {
      const evs = await readEvents(app)
      const s = evs.find((e) => e.type === 'sandbox-state')
      return s && s.type === 'sandbox-state'
        ? { envDisabled: s.envDisabled, argvNoSandbox: s.argvNoSandbox }
        : null
    },
    async waitForEmit(channel, timeoutMs = 10_000) {
      const deadline = performance.now() + timeoutMs
      for (;;) {
        // Payloads live in the test-only capture buffer, not the main log
        // (which retains only size + hash for emit — see P0-3).
        const caps = await readTestEmits(app)
        const hit = caps.find((e) => e.channel === channel)
        if (hit) return hit.data
        if (performance.now() > deadline) {
          const evs = await readEvents(app)
          throw new Error(`timed out waiting for emit on "${channel}"; saw: ${JSON.stringify(evs)}`)
        }
        await sleep(100)
      }
    },
    async emitsOn(channel) {
      const caps = await readTestEmits(app)
      return caps.filter((e) => e.channel === channel).map((e) => e.data)
    },
    bounds: () =>
      app.evaluate(async (electron) => {
        const cage = (electron.app as unknown as { __cage?: { bounds: unknown } }).__cage
        return (cage ? cage.bounds : { chrome: null, cage: null, window: null }) as never
      }),
    close: async () => {
      await app.close()
      rmSync(casDir, { recursive: true, force: true })
    }
  }
  return handle
}

function canaryArg(c: Canary | undefined): Record<string, string> | null {
  if (!c) return null
  return { http: c.http, ws: c.ws, stun: c.stun }
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms))
}

// ── Fixtures ─────────────────────────────────────────────────────────────────
// `canary` starts/stops a fresh listener per test. `open` launches cages and
// guarantees every one is closed at test end, even on failure.
export const test = base.extend<{
  canary: Canary
  open: (opts: LaunchOptions) => Promise<CageHandle>
}>({
  canary: async ({}, use) => {
    const c = await startCanary()
    await use(c)
    await c.close()
  },
  open: async ({ canary }, use) => {
    const opened: CageHandle[] = []
    const openFn = async (opts: LaunchOptions): Promise<CageHandle> => {
      const h = await launch({ canary, ...opts })
      opened.push(h)
      return h
    }
    await use(openFn)
    for (const h of opened) await h.close().catch(() => {})
  }
})

export { expect } from '@playwright/test'
